version: "3"
services:
  api_getway:
    container_name: api_getway
    build: ./api_getway/DayscoolAPI
    ports:
      - "5000:5000"

  ms_user_db:
    container_name: ms_user_db
    image: "mysql:latest"
    restart: always
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    volumes:
      - ./front-end/ms_user/ms_user_generator:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: ms_user_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 153486
      MYSQL_ROOT_PASSWORD: 153486
      MYSQL_ROOT_HOST: "%"

  ms_user:
    container_name: ms_user
    build: ./back-end/ms_user/
    ports:
      - "10100:10100"

  ms_cursos:
    container_name: ms_cursos
    build: ./back-end/ms_cursos
    ports:
      - "8000:8000"

  ms_authentication:
    container_name: ms_authentication
    build: ./back-end/ms_authentication/demo
    ports:
      - "10200:10200"

  ms_notification:
    container_name: ms_notification
    build: ./back-end/ms_notification
    ports:
      - "3000:3000"

  ms_message:
    container_name: ms_message
    build: ./back-end/ms_message
    ports:
      - "4000:4000"
    env_file: ./back-end/ms_message/env_vars.env

  ms_activities:
    container_name: ms_activities
    build: ./back-end/ms_actividades
    ports:
      - "8080:8080"
  sa-ldap:
    image: osixia/openldap
    container_name: sa_ldap
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Software Architecture"
      LDAP_DOMAIN: "arqsoft.unal.edu.co"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "arqsoft.unal.edu.co"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldap_client
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "sa-ldap"
      PHPLDAPADMIN_HTTPS: "false"
      ServerName: "arqsoft.unal.edu.co"
    ports:
      - "8085:80"
    links:
      - sa-ldap
  # ms_abac:
  #   container_name: ms_abac
  #   build: ./back-end/ms_abac
  #   ports:
  #     # Mapping the port to make the Phoenix app accessible outside of the container
  #     - "80:80"


networks:
  default:
    external:
      name: dayscool
