version: "3"
services:
  api_getway:
    container_name: api_getway
    build: ./api_getway/DayscoolAPI
    ports:
      - "5000:5000"

  ms_user_db:
    container_name: ms_user_db
    image: "mysql:latest"
    restart: always
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    volumes:
      - ./front-end/ms_user/ms_user_generator:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: ms_user_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 153486
      MYSQL_ROOT_PASSWORD: 153486
      MYSQL_ROOT_HOST: "%"

  ms_user:
    container_name: ms_user
    build: ./back-end/ms_user/
    ports:
      - "10100:10100"

  ms_cursos:
    container_name: ms_cursos
    build: ./back-end/ms_cursos
    ports:
      - "8000:8000"

  ms_authentication:
    container_name: ms_authentication
    build: ./back-end/ms_authentication/demo
    ports:
      - "10200:10200"

  ms_notification:
    container_name: ms_notification
    build: ./back-end/ms_notification
    ports:
      - "3000:3000"

  ms_message:
    container_name: ms_message
    build: ./back-end/ms_message
    ports:
      - "4000:4000"
    env_file: ./back-end/ms_message/env_vars.env

  ms_activities:
    container_name: ms_activities
    build: ./back-end/ms_actividades
    ports:
      - "8080:8080"

networks:
  default:
    external:
      name: dayscool
